name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create resource placeholders
        run: |
          New-Item -ItemType Directory -Force resources/java21
          New-Item -ItemType Directory -Force resources/mods
      - run: npm ci
      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build && npx electron-builder --win --publish always

  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Linux build deps
        run: sudo apt-get install -y libarchive-tools fakeroot
      - name: Create resource placeholders
        run: mkdir -p resources/java21 resources/mods
      - run: npm ci
      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build && npx electron-builder --linux --publish always

  release-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create resource placeholders
        run: mkdir -p resources/java21 resources/mods
      - run: npm ci
      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run build && npx electron-builder --mac --publish always
